services:
  - type: web
    name: fraud-detector-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: GROQ_API_KEY
        sync: false # You will need to add this manually in the Render dashboard!
